### ISSUE TITLE
Showroom Page

### ISSUE THREAD

**Issue by nawissor** [nawissor/midnightowl#61]
Create a showroom page with images of websites that has been completed

**Comment by nawissor** [comment]
Remember to change the crumbs menu and structured data for the page.

**Comment by nawissor** [comment]
Add a vigentte effect to the showroom boxes on the showroom page @iwanross :
https://codepen.io/Ragnarokkr/pen/KAejm

**Comment by nawissor** [comment]
See this structured markup example:

<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "ItemList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": "1",
      "item": {
        "@type": "website",
        "url": "http://www.midnightowl.co.za/showroom#rent-a-guide",
        "name": "Strawberry Mango Pie",
        "image": "http://example.com/recipes/smm.jpg",
        "author": {
                    "@type": "LocalBusiness",
          "name": "Midnisht Owl",
           "image": "http://www.midnightowl.co.za/images/Web-Design-Development.jpg",
           "logo": "http://www.midnightowl.co.za/images/owl-silhouette256x256.png",
           "priceRange" : "Between R750 and R3500",
           "telephone": "021 302 7897",
             "address": {
    "@type": "PostalAddress",
    "streetAddress": "29 Doris Drive Wellington",
    "postOfficeBoxNumber": "1160",
    "addressLocality": "Wellington",
    "addressRegion": "Western Cape",
    "postalCode": "7655",
    "addressCountry": "South Africa"
  }
          
          
          },
        "datePublished": "2010-03-03",
        "description": "Delicious strawberry mango pie."  
       
 
      }
    },
      {
      "@type": "ListItem",
      "position": "1",
      "item": {
        "@type": "website",
        "url": "http://www.midnightowl.co.za/showroom#stomer-nursery",
        "name": "Strawberry Mango Pie",
        "image": "http://example.com/recipes/smm.jpg",
        "author": {
                    "@type": "LocalBusiness",
          "name": "Midnisht Owl",
           "image": "http://www.midnightowl.co.za/images/Web-Design-Development.jpg",
           "logo": "http://www.midnightowl.co.za/images/owl-silhouette256x256.png",
           "priceRange" : "Between R750 and R3500",
           "telephone": "021 302 7897",
             "address": {
    "@type": "PostalAddress",
    "streetAddress": "29 Doris Drive Wellington",
    "postOfficeBoxNumber": "1160",
    "addressLocality": "Wellington",
    "addressRegion": "Western Cape",
    "postalCode": "7655",
    "addressCountry": "South Africa"
  }
          
          
          },
        "datePublished": "2010-03-03",
        "description": "Delicious strawberry mango pie."  
       
 
      }
    },
    {
      "@type": "ListItem",
      "position": "2",
      "item": {
        "@type": "website",
        "url": "http://www.midnightowl.co.za/showroom#royal-dress-hire",
        "name": "Classic Mac and Cheese",
        "image": "http://example.com/recipes/mac-and-cheese.jpg",
        "author": {
          "@type": "LocalBusiness",
          "name": "Midnisht Owl",
           "image": "http://www.midnightowl.co.za/images/Web-Design-Development.jpg",
           "logo": "http://www.midnightowl.co.za/images/owl-silhouette256x256.png",
           "priceRange" : "Between R750 and R3500",
           "telephone": "021 302 7897",
             "address": {
    "@type": "PostalAddress",
    "streetAddress": "29 Doris Drive Wellington",
    "postOfficeBoxNumber": "1160",
    "addressLocality": "Wellington",
    "addressRegion": "Western Cape",
    "postalCode": "7655",
    "addressCountry": "South Africa"
  }
          
          
          },
          
        "datePublished": "2017-06-03",
        "description": "Classic baked macaroni recipe."   
   
      }
    }
  ]
}
</script>

**Comment by iwanross** [comment]
Add a **separate Carousel** for the garden room coffee shop.  Take a screen shot of the home page. 
![garden-room-coffee-shop](https://user-images.githubusercontent.com/31855529/33239607-18a7fe18-d2ae-11e7-8a4d-9c8df6bbf893.jpg)

**Comment by iwanross** [comment]
Add the structured data @nawissor  afterwards. The site looks good!

**Comment by iwanross** [comment]
Fix duplicated url list for list items in structured markup @nawissor 
![structured-data-errors](https://user-images.githubusercontent.com/31855529/33240032-8e4deaac-d2b7-11e7-8c69-f5b5892ed6d3.jpg)
